# Generated by Django 5.2.13 on 2026-07-29 14:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
                ('start_year', models.PositiveIntegerField(help_text='Calendar year the May start falls in')),
                ('closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(help_text='Kept even if the account is removed', max_length=150)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('target', models.CharField(max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='hub.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='hub.appraisalyear')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GoalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_assignments', to='hub.employee')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hub.goal')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='assignees',
            field=models.ManyToManyField(related_name='goals', through='hub.GoalAssignment', to='hub.employee'),
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('text', models.CharField(max_length=400)),
                ('max_marks', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('quarterly', models.BooleanField(default=False)),
                ('scoring_mode', models.CharField(choices=[('manual', 'Scored manually'), ('from_tasks', 'Scored from approved tasks')], default='manual', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='hub.goal')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_index', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='hub.employee')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='hub.kpi')),
                ('scored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee', 'kpi', 'month_index'],
            },
        ),
        migrations.CreateModel(
            name='ScoredMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_index', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_months', to='hub.employee')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_months', to='hub.appraisalyear')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('submitted', 'Awaiting approval'), ('approved', 'Approved'), ('returned', 'Sent back')], default='not_started', max_length=12)),
                ('scoring_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hub.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='hub.kpi')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hub.appraisalyear')),
            ],
            options={
                'ordering': ['scoring_month', 'due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('proposed_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('submitted', 'Awaiting approval'), ('approved', 'Approved'), ('returned', 'Sent back')], default='approved', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('returned', 'Sent back')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_updates', to='hub.employee')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='hub.task')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='goalassignment',
            constraint=models.UniqueConstraint(fields=('goal', 'employee'), name='uniq_goal_assignment'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('year', 'code'), name='uniq_goal_code_per_year'),
        ),
        migrations.AddConstraint(
            model_name='kpi',
            constraint=models.UniqueConstraint(fields=('goal', 'code'), name='uniq_kpi_code_per_goal'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('employee', 'kpi', 'month_index'), name='uniq_score_per_kpi_month'),
        ),
        migrations.AddConstraint(
            model_name='scoredmonth',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month_index'), name='uniq_scored_month'),
        ),
    ]
