# Generated by Django 5.2.13 on 2026-08-13 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_yearacknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
