# Generated by Django 5.2.13 on 2026-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_task_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupdate',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('returned', 'Sent back'), ('not_needed', 'Progress update')], default='pending', max_length=10),
        ),
    ]
