# Generated by Django 5.2.13 on 2026-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_alter_taskupdate_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('picked_up', 'Task picked up'), ('in_progress', 'In progress'), ('near_done', 'Near completion'), ('submitted', 'Awaiting review'), ('approved', 'Approved'), ('returned', 'Sent back')], default='not_started', max_length=12),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='proposed_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('picked_up', 'Task picked up'), ('in_progress', 'In progress'), ('near_done', 'Near completion'), ('submitted', 'Awaiting review'), ('approved', 'Approved'), ('returned', 'Sent back')], default='approved', max_length=12),
        ),
    ]
