# Generated by Django 5.2.13 on 2026-08-13 16:41

from django.db import migrations, models


def rename_near_done(apps, schema_editor):
    """"Near completion" became "On track". Rows written before the rename hold
    the old value, and a status not in STATUS_CHOICES renders as a raw string."""
    apps.get_model("hub", "Task").objects.filter(status="near_done").update(status="on_track")
    apps.get_model("hub", "TaskUpdate").objects.filter(
        proposed_status="near_done").update(proposed_status="on_track")


def back_to_near_done(apps, schema_editor):
    apps.get_model("hub", "Task").objects.filter(status="on_track").update(status="near_done")
    apps.get_model("hub", "TaskUpdate").objects.filter(
        proposed_status="on_track").update(proposed_status="near_done")


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_alter_task_status_alter_taskupdate_proposed_status'),
    ]

    operations = [
        migrations.RunPython(rename_near_done, back_to_near_done),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('picked_up', 'Task picked up'), ('in_progress', 'In progress'), ('on_track', 'On track'), ('submitted', 'Sent for review'), ('approved', 'Completed'), ('returned', 'Sent back')], default='not_started', max_length=12),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='proposed_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('picked_up', 'Task picked up'), ('in_progress', 'In progress'), ('on_track', 'On track'), ('submitted', 'Sent for review'), ('approved', 'Completed'), ('returned', 'Sent back')], default='approved', max_length=12),
        ),
    ]
