# Generated by Django 5.2.13 on 2026-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_status_on_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupdate',
            name='proposed_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('picked_up', 'Task picked up'), ('in_progress', 'In progress'), ('on_track', 'On track'), ('submitted', 'Sent for review'), ('approved', 'Completed'), ('returned', 'Sent back')], default='approved', max_length=12),
        ),
    ]
